# Generated by Django 5.1.1 on 2024-09-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('surname', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('guardian_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
