# Generated by Django 5.1.1 on 2024-09-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_result_delete_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(choices=[('2024/2025', 'SESSION_2024_2025'), ('2025/2026', 'SESSION_2025_2026')], max_length=20),
        ),
    ]
