# Generated by Django 5.1.1 on 2024-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_subject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
