# Generated by Django 5.1.1 on 2024-09-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('surname', models.CharField(max_length=50)),
                ('other_names', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
